### ISSUE TITLE
[Feature] Custom provider DNS challenge

### ISSUE THREAD

**Issue by ruben-janssens** [pulumiverse/pulumi-acme#23]
Currently it is only possible to use pre defined providers to create the records for DNS-01.
Is it possible to add a custom provider (Dynamic Resource Providers) to this because our use case requires a different DNS provider.

Possible implementation for `CertificateDnsChallengeArgs`:
```python
CertificateDnsChallengeArgs(
    provider="custom",
    config={
      "resource": <resource-class>,
      "args": <args-class>
    }
)
```

Or a two step solution that allows us to create the records and then do the verification and create the certificate.

**Comment by ringods** [comment]
@ruben-janssens this provider bridges the upstream Terraform ACME provider. Whatever is available by the TF provider for cert challenges, is available here.

If you want to see this come to light, please file a similar request upstream: https://github.com/vancluever/terraform-provider-acme

**Comment by ruben-janssens** [comment]
Thanks for the response! In that case I will have to look for another solution because it will not be likely to happen.
