### ISSUE TITLE
Package names in README.md are incorrect + `docs` folder missing

### ISSUE THREAD

**Issue by ringods** [pulumiverse/pulumi-acme#3]
Hello @dbeattie71,

I just noticed that the package names for the different SDKs don't match the ones specified in `resources.go`:

https://github.com/pulumiverse/pulumi-acme/blob/eba7a2be388dd547a2cd7284b72cb3d5e5b99fb1/provider/resources.go#L118-L154

Can you update the README?

Together with it, can you add a `docs` folder and provide 2 Markdown files, named exactly like the ones from [this provider](https://github.com/pulumiverse/pulumi-unifi/tree/main/docs) but with the content updated for the ACME provider?

**Comment by dbeattie71** [comment]
I'll get it fixed.  Currently, unless I roll back the terraform provider version, this provider won't work because of the -dnsplugin issue.  I haven't had a chance to try the suggestions for that yet.
